<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>apichaning</groupId>
  <artifactId>apichaning</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <dependencies>
  <!-- Source: https://mvnrepository.com/artifact/io.rest-assured/rest-assured -->
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <version>4.3.0</version>
    </dependency>
<!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.3.0</version>
 </dependency>
<!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
  	<dependency>
  		<groupId>com.local</groupId>
  		<artifactId>Local</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  <dependency>
  <groupId>io.rest-assured</groupId>
  		<artifactId>json-schema-validator</artifactId>
  		<version>4.3.1</version>
  </dependency>
  
  <dependency>
            <groupId>com.github.scribejava</groupId>
            <artifactId>scribejava-apis</artifactId>
            <version>2.5.3</version>
            <scope>test</scope>
</dependency>
  
  
  
  <dependency>
  	<groupId>Frameworks</groupId>
  	<artifactId>Frameworks</artifactId>
  	<version>0.0.1-SNAPSHOT</version>
  </dependency>
  
  </dependencies>
  
  
</project>